
server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dosa_fulfiller
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      #ddl-auto: validate
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE